---
title: "SQL - Exercices"
date: '`r stringr::str_to_title(format(Sys.Date(), "%B %Y"))`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Le vélo STAR

Nous considérons les données des stations de vélos en libre service STAR de la ville de Rennes. Une copie de la base SQLite est disponible dans le fichier `LEveloSTAR.sqlite3`. Utiliser les fonctions du package `DBI` pour répondre aux questions suivantes.

1. Se connecter à la base de données et afficher les tables. Pour chaque table, afficher les variables.

2. Sélectionner l'identifiant `id`, le nom `nom` et l'identifiant de la station proche `id_proche_1` depuis la table `Topologie`.

3. Faire une jointure pour créer une table qui contient la liste des stations avec l'identifiant, le nom et le nom de la station proche associée à l'identifiant `id_proche_1` de la table `Topologie`.

4. Ajouter à la table précédente la distance euclidienne entre la station et la station proche associée à l'identifiant `id_proche_1` de la table `Topologie`.

5. Nous nous trouvons au point de coordonnées (48.1179151,-1.7028661). Créer une table avec le nom des trois stations les plus proches classées par ordre de distance et le nombre d'emplacements libres dans ces stations.

6. Reprendre les questions précédentes en utilisant les fonctions de `dplyr`.

7. Terminer correctement en fermant la connexion à la base de données.

## Musique

Sur le site https://github.com/lerocha/chinook-database, nous pouvons trouver des bases de données de bibliothèques musicales. Une copie de la base SQLite est disponible dans le fichier `Chinook_Sqlite.sqlite`.

1. Se connecter à la base de données et afficher les tables. Explorer le jeu de données pour le découvrir. En particulier, étudier comment les tables `Playlist`, `PlaylistTrack` et `Track` sont liées.

2. Utiliser les verbes de `dplyr` pour savoir quelles sont les playlists qui contiennent le plus de pistes.

3. En utilisant `dplyr`, construire une table contenant les informations suivantes sur la playlist appelée `Classical` : le titre de chaque piste ainsi que le titre de l’album dont cette piste est tirée.

4. Même question en écrivant directement la requête en SQL.

5. Terminer correctement en fermant la connexion à la base de données.